### ISSUE TITLE
All param are "any" in js files

### ISSUE THREAD

**Issue by SelaO** [joelday/vscode-docthis#128]
I have js file with ES5 and ES6 classes, in both cases, I always get "any" as the params of functions. 

Is there a way for it to recognize the types of the arguments?

**Comment by joelday** [comment]
@SelaO unfortunately this won't be possible for .js files because even if the extension were currently able to examine types implicitly (without any type annotation), the function signature types can't be inferred from the inside out.

If I'm not mistaken, it might be possible to do this if https://github.com/facebook/flow were added for the purposes of examining the symbolic tree of .js documents.
